import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";

// Load the Hanken Grotesk font from Google
const hankenGrotesk = Hanken_Grotesk({
  subsets: ['latin'], // You can add other subsets if necessary
  weight: ['400', '700'], // Adjust the font weights as needed
  variable: '--font-hanken-grotesk',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${hankenGrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
